Fix: KeyError: Config 'DISPATCH_ENCRYPTION_KEY' is missing (#127)
Fix this error during install.sh

Creating dispatch_web_run ... done
Traceback (most recent call last):
  File "/usr/local/bin/dispatch", line 5, in <module>
    from dispatch.cli import entrypoint
  File "/usr/local/lib/python3.9/site-packages/dispatch/cli.py", line 6, in <module>
    from dispatch import __version__, config
  File "/usr/local/lib/python3.9/site-packages/dispatch/config.py", line 99, in <module>
    DISPATCH_ENCRYPTION_KEY = config("DISPATCH_ENCRYPTION_KEY", cast=Secret)
  File "/usr/local/lib/python3.9/site-packages/starlette/config.py", line 64, in __call__
    return self.get(key, cast, default)
  File "/usr/local/lib/python3.9/site-packages/starlette/config.py", line 77, in get
    raise KeyError(f"Config '{key}' is missing, and has no default.")
KeyError: "Config 'DISPATCH_ENCRYPTION_KEY' is missing, and has no default."
ERROR: 1
Cleaning up...